### ISSUE TITLE
More details with pics or vids

### ISSUE THREAD

**Issue by ashrafalzyoud** [petoc/redmine-http-integration#1]
Thx for your plugin and for new idea 💡
But can u tell us more details
And the external http what the benefits
I wanna see the output

**Comment by petoc** [comment]
There is not much to show here.
When enabled, in case od issue change, Redmine will just call configured URL and in case of POST method, it will also include JSON with issue detail (similar to issue detail in Redmine API).
External system can call Redmine API or in case of POST request, just use information from JSON to synchronize changed issue.
