### ISSUE TITLE
not working

### ISSUE THREAD

**Issue by ashrafalzyoud** [petoc/redmine-http-integration#3]
![image](https://github.com/petoc/redmine-http-integration/assets/50211455/9c0c58d1-dd63-454b-be43-d5ef01c139c4)
 IM install your plugin and try it
same this pics

but nothings happend no any notifications

**Comment by ashrafalzyoud** [comment]
any update @petoc

**Comment by petoc** [comment]
Hard to tell what could be causing issue for you based on screenshot.
Could be network related issue, for example if using Redmine in docker container, maybe IP address defined in plugin config is unreachable for Redmine, but it is unrelated to plugin itself.
